version: "3"
services:
  vendor-portal:
    image: simba195/selenium
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=vendor-portal.xml
    volumes:
      - C:/Users/benny/workspace/05-dockerize/grid-and-test-suites/output-vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: simba195/selenium
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=4
    - TEST_SUITE=flight-reservation.xml
    volumes:
      - C:/Users/benny/workspace/05-dockerize/grid-and-test-suites/output-flight-reservation:/home/selenium-docker/test-output
